=== jozefzatko/page-flow-project/page-flow-project/page-flow-project/page-flow-project/core/src/main/resources/schema/index_schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-06/schema#",
  "type": "object",
  "$id": "http://example.com/example.json",
  "properties": {
    "author": {
      "$id": "/properties/author",
      "type": "string"
    },
    "description": {
      "$id": "/properties/description",
      "type": "string"
    },
    "fileTypes": {
      "$id": "/properties/fileTypes",
      "items": {
        "$id": "/properties/fileTypes/items",
        "properties": {
          "fileItems": {
            "$id": "/properties/fileTypes/items/properties/fileItems",
            "items": {
              "$id": "/properties/fileTypes/items/properties/fileItems/items",
              "properties": {
                "fileName": {
                  "$id": "/properties/fileTypes/items/properties/fileItems/items/properties/fileName",
                  "type": "string"
                },
                "filePath": {
                  "$id": "/properties/fileTypes/items/properties/fileItems/items/properties/filePath",
                  "type": "string"
                }
              },
              "type": "object"
            },
            "type": "array"
          },
          "fileNameRegex": {
            "$id": "/properties/fileTypes/items/properties/fileNameRegex",
            "type": "string"
          },
          "filePathRegex": {
            "$id": "/properties/fileTypes/items/properties/filePathRegex",
            "type": "string"
          },
          "fileTypeDescription": {
            "$id": "/properties/fileTypes/items/properties/fileTypeDescription",
            "type": "string"
          },
          "fileTypeName": {
            "$id": "/properties/fileTypes/items/properties/fileTypeName",
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "array"
    },
    "projectName": {
      "$id": "/properties/projectName",
      "type": "string"
    },
    "rootDirectory": {
      "$id": "/properties/rootDirectory",
      "type": "string"
    }
  }
}

=== jozefzatko/page-flow-project/page-flow-project/page-flow-project/page-flow-project/data/index_config.json
{
	"projectName": "Spring Greenhouse",
	"description": "https://github.com/spring-projects/greenhouse",
	"author": "Jozef Za≈•ko",
	"rootDirectory": "//greenhouse",
	"fileTypes": [{
			"fileTypeName": "Java Source File",
			"fileTypeDescription": "All Java source files from src/main/java directory",
			"fileNameRegex": "^[A-Z].+\\.java",
			"filePathRegex": "^src\\\\main\\\\java.+"
		}, {
			"fileTypeName": "JUnit Test File",
			"fileTypeDescription": "All JUnit test files from src/test/java directory",
			"fileNameRegex": "^[A-Z].+\\.java",
			"filePathRegex": "^src\\\\test\\\\java.+"
		}, {
			"fileTypeName": "JSP Source File",
			"fileTypeDescription": "All JSP source files from src/main/webapp/WEB-INF/view directory",
			"fileNameRegex": "^[^\\.]+\\.jsp",
			"filePathRegex": "^src\\\\main\\\\webapp\\\\WEB-INF\\\\views.+"
		},
		{
			"fileTypeName": "Tiles: Common JSP Source File",
			"fileTypeDescription": "All JSP source files from src/main/webapp/layouts/standard directory",
			"fileNameRegex": "^[^\\.]+\\.jsp",
			"filePathRegex": "^src\\\\main\\\\webapp\\\\WEB-INF\\\\layouts\\\\standard.+"
		},
		{
			"fileTypeName": "JS Source File",
			"fileTypeDescription": "All JS source files from src/main/webapp directory",
			"fileNameRegex": "^[^\\.]+\\.js",
			"filePathRegex": "^src\\\\main\\\\webapp.+"
		},
		{
			"fileTypeName": "tiles.xml",
			"fileTypeDescription": "Apache Tiles config file for views",
			"fileNameRegex": "tiles.xml",
			"filePathRegex": "^src\\\\main\\\\webapp\\\\WEB-INF\\\\views.+"
		}
	]
}

=== jozefzatko/page-flow-project/page-flow-project/page-flow-project/page-flow-project/indexer/src/test/resources/test_index_config.json
{
  "projectName": "Spring Greenhouse",
  "description": "https://github.com/spring-projects/greenhouse",
  "author": "Jozef Za≈•ko",
  "rootDirectory": "//greenhouse",
  "fileTypes": [
    {
      "fileTypeName": "Java Source File",
      "fileTypeDescription": "All Java source files from src/main/java directory",
      "fileNameRegex": "^[A-Z].+\\.java",
      "filePathRegex": "^src\\\\main\\\\java.+"
    },
    {
      "fileTypeName": "JSP Source File",
      "fileTypeDescription": "All JSP source files from src/main/webapp/WEB-INF/view directory",
      "fileNameRegex": "^[^\\.]+\\.jsp",
      "filePathRegex": "^src\\\\main\\\\webapp\\\\WEB-INF\\\\views.+"
    }
  ]
}
