=== jozefzatko/page-flow-project/page-flow-project/page-flow-project/page-flow-project/core/src/main/resources/schema/mgfsm_config_schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://example.com/example.json",
  "type": "object",
  "properties": {
    "appLocation": {
      "id": "/properties/appLocation",
      "type": "string"
    },
    "inputLocation": {
      "id": "/properties/inputLocation",
      "type": "string"
    },
    "outputLocation": {
      "id": "/properties/outputLocation",
      "type": "string"
    },
    "paramsList": {
      "id": "/properties/optionList",
      "type": "array",
      "items": {
        "id": "/properties/optionList/items",
        "type": "object",
        "properties": {
          "name": {
            "id": "/properties/optionList/items/properties/name",
            "type": "string"
          },
          "shortHand": {
            "id": "/properties/optionList/items/properties/shortHand",
            "type": "string"
          },
          "value": {
            "id": "/properties/optionList/items/properties/value",
            "type": "string"
          },
          "description": {
            "id": "/properties/optionList/items/properties/description",
            "type": "string"
          }
        }
      }
    }
  }
}

=== jozefzatko/page-flow-project/page-flow-project/page-flow-project/page-flow-project/data/mgfsm_config.json
{
  "appLocation":"-",
  "inputLocation":"-",
  "outputLocation":"-",
  "paramsList":[
    {
      "name":"support",
      "shortHand":"s",
      "value":"2",
      "description":"The minimum number of times the sequence to be mined must be present in the Database"
    },
    {
      "name":"gamma",
      "shortHand":"g",
      "value":"0",
      "description":"The maximum amount of gap that can be taken for a sequence to be mined by MG-FSM"
    },
    {
      "name":"lambda",
      "shortHand":"l",
      "value":"20",
      "description":"The maximum length of the sequence to be mined is determined by the this parameter."
    }
  ]
}
